# =========== normal setting ===========
net_mode: ds_diff   # 记得修改噢
Task_name: BraTs_synthesis
Task_id: 60
cuda_idx: 1
fold_K: 5
fold_idx: 1
vae_local_pretrained: False
# =========== test setting ===========
use_prostate_mask: False
ckpt_name: 'checkpoint' # best checkpoint
test_num:
test_batch_size: 64
dataset_type: normal
sampler_setting:
  sampler: "ddim"
  ddim_use_original_steps: False
  sample_steps: 20
  ddim_eta: 0
# path
dir_prefix:
result_path:
filepath_img:
h5_2d_img_dir:
image_size: 192   #no use
# =========== optim setting ============
seed: 2024
# ============= never touched config ===============
mode: test


