attention_resolutions: 32,16,8
base_samples: ''
batch_size: 10
clip_denoised: true
data_dir: ''
diffusion_steps: 1000
dropout: 0.0
hr_data_dir: /home/user4/sharedata/newnas_1/MJY_file/IXI_dataset/IXI_testing_hr_t2_scale_by_4_imgs-004.npy
lr_data_dir: /home/user4/sharedata/newnas_1/MJY_file/IXI_dataset/IXI_testing_lr_t2_scale_by_4_imgs-001.npy
other_data_dir: /home/user4/sharedata/newnas_1/MJY_file/IXI_dataset/IXI_testing_hr_t1_scale_by_4_imgs-003.npy
image_size: 224
in_channel: 1
learn_sigma: true
model_path: /home/user4/sharedata/newnas_1/MJY_file/SOTA_models/DiscDiff/x4_IXI/model130000.pt
noise_schedule: linear
num_channels: 96
num_head_channels: 48
num_heads: 4
num_heads_upsample: -1
num_res_blocks: 2
num_samples: 50000
predict_xstart: false
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
sampling_method: ddim
timestep_respacing: '20'
use_checkpoint: false
use_fp16: false
use_kl: false
use_scale_shift_norm: true
