attention_resolutions: 32,16,8
batch_size: 6
data_dir: ''
diffusion_steps: 1000
dropout: 0.0
ema_rate: '0.9999'
fp16_scale_growth: 0.001
ce_data_dir: /home/user4/sharedata/newnas_1/MJY_file/BraTs_dataset_npy/train_ce_data.npy
t1_data_dir: /home/user4/sharedata/newnas_1/MJY_file/BraTs_dataset_npy/train_t1_data.npy
t2_data_dir: /home/user4/sharedata/newnas_1/MJY_file/BraTs_dataset_npy/train_t2_data.npy
dwi_data_dir: /home/user4/sharedata/newnas_1/MJY_file/BraTs_dataset_npy/train_dwi_data.npy
data_config:
  { "K": 5,
    "random_state": 2024,
    "train_dir": "/home/user4/sharedata/newnas_1/MJY_file/BraTs_dataset_npy/",
    "fold": 1 }
image_size: 224
in_channel: 1
learn_sigma: true
log_interval: 50
lr: 0.0001
lr_anneal_steps: 0
microbatch: -1
noise_schedule: linear
num_channels: 96
num_head_channels: 48
num_heads: 4
num_heads_upsample: -1
num_res_blocks: 2
predict_xstart: false
parameterization: "v"
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
resume_checkpoint: ''
save_interval: 10000
schedule_sampler: uniform
timestep_respacing: ''
use_checkpoint: false
use_fp16: false
use_kl: false
use_scale_shift_norm: true
weight_decay: 0.0
